<a href="https://colab.research.google.com/github/manzer07/This/blob/main/Customer_sample_datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/Customer_sample")

In [ ]:
df.head()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
0,1,Mrs,Eb,Torre,63,MALE,etorre0@domainmarket.com,1,36945.54,229.34.127.166,890-424-8695,265 Gulseth Plaza,Nezhinka,NaN,460536,Russia
1,2,Ms,Bartholemy,Dmiterko,29,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,NaN,NaN,Georgia
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19447.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,Madelyn,Helstrip,52,FEMALE,mhelstrip3@purevolume.com,3,29868.55,167.49.197.203,375-528-2018,8713 Jenifer Terrace,Żółkiewka,NaN,22-335,Poland
4,5,Dr,Aeriell,Doran,41,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,NaN,NaN,Peru

In [ ]:
df.tail()

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
14008,14009,Dr,Mill,McManamen,Do not want to specify,MALE,mmcmanamenrn@intel.com,1,26503.69,233.139.238.253,425-990-4341,86 Gina Drive,Yazykovo,NaN,453444,Russia
14009,14010,Dr,Ugo,Bern,54,MALE,ubernro@cpanel.net,3,25798.50,224.98.187.220,400-589-7549,74022 Vahlen Park,Kaesŏng,NaN,NaN,North Korea
14010,14011,Mr,Star,Brotherhood,35,FEMALE,sbrotherhoodrp@skyrock.com,2,31947.77,205.111.252.186,404-365-1886,23 Maywood Hill,Ar Rumaythīyah,NaN,NaN,Kuwait
14011,14012,Rev,Woodie,O'Brogan,31,MALE,wobroganrq@clickbank.net,0,17699.67,191.40.46.71,745-344-9601,8 Chinook Trail,Behābād,NaN,NaN,Iran
14012,14013,Mrs,Vikki,Winsom,31,FEMALE,vwinsomrr@elegantthemes.com,Not Available,22796.39,102.49.86.71,224-869-6773,433 Wayridge Place,Kitapak,NaN,6711,Philippines

In [ ]:
df.shape

(14013, 16)

In [ ]:
df.columns

Index(['Customer Id', 'title', 'first_name', 'last_name', 'Age', 'gender',
       'email', 'Other members in Family', 'Annual Average Spend',
       'ip_address', 'phone_number', 'address', 'city', 'state', 'postal_code',
       'country'],
      dtype='object')

#Customer ID

In [ ]:
#check if the customer is null or not
#if null then sort it
#ascending order sort it
df['Customer Id'].values

array([    1,     2,     3, ..., 14011, 14012, 14013])

In [ ]:
df['Customer Id'].isnull().sum()

np.int64(0)

In [ ]:
df['Customer Id'].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
14008    False
14009    False
14010    False
14011    False
14012    False
Name: Customer Id, Length: 14013, dtype: bool

In [ ]:
df['Customer Id']

0            1
1            2
2            3
3            4
4            5
         ...
14008    14009
14009    14010
14010    14011
14011    14012
14012    14013
Name: Customer Id, Length: 14013, dtype: int64

#Title

In [ ]:
df['title'].values

array(['Mrs', 'Ms', nan, ..., 'Mr', 'Rev', 'Mrs'], dtype=object)

In [ ]:
df['title'].isnull().sum()

np.int64(2304)

In [ ]:
df['title'].unique()

array(['Mrs', 'Ms', nan, 'Dr', 'Mr', 'Rev', 'Title'], dtype=object)

In [ ]:
# Map gender to title, falling back to 'N/A' if gender is neither male nor female
df['title'] = np.where(
    df['title'].isnull(),
    np.where(
        df['gender'].str.upper().isin(['MALE']),
        'Mr',
        np.where(
            df['gender'].str.upper().isin(['FEMALE']),
            'Mrs',
            'N/A'
        )
    ),
    df['title']
)

In [ ]:
df['title'].unique()

array(['Mrs', 'Ms', 'N/A', 'Dr', 'Mr', 'Rev', 'Title'], dtype=object)

In [ ]:
df['title'].isnull().sum()

np.int64(0)

#First name

In [ ]:
df['first_name'].values

array(['Eb', 'Bartholemy', nan, ..., 'Star', 'Woodie', 'Vikki'],
      dtype=object)

In [ ]:
df['first_name'].isnull().sum()

np.int64(5)

In [ ]:
df[df['first_name'].isnull()]

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
2,3,N/A,NaN,NaN,NaN,NaN,NaN,NaN,19447.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,87,N/A,NaN,NaN,NaN,NaN,NaN,NaN,34901.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8145,8146,N/A,NaN,NaN,NaN,NaN,NaN,NaN,29570.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11381,11382,N/A,NaN,NaN,NaN,NaN,NaN,NaN,38223.46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13638,13639,N/A,NaN,NaN,NaN,NaN,NaN,NaN,12330.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df.drop(index=[2,86,8145,11381,13638])

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df['first_name'].duplicated().sum()

np.int64(7265)

In [ ]:
df['first_name'].unique()

array(['Eb', 'Bartholemy', 'Madelyn', ..., 'Rafaello', 'Decca', 'Ugo'],
      dtype=object)

In [ ]:
df['first_name'].isnull().sum()

np.int64(0)

#Last Name

In [ ]:
df['last_name'].values

array(['Torre', 'Dmiterko', 'Helstrip', ..., 'Brotherhood', "O'Brogan",
       'Winsom'], dtype=object)

In [ ]:
df['last_name'].isnull().sum()

np.int64(0)

In [ ]:
df[['first_name', 'last_name']].duplicated().sum()

np.int64(13)

In [ ]:
df[df.duplicated(subset=['first_name', 'last_name'], keep=False)]

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
998,1001,Title,first_name,last_name,40,MALE,email,0,20513.56,ip_address,phone_number,address,city,state,postal_code,country
1999,2002,Title,first_name,last_name,40,GENDER,email,2,29818.95,ip_address,phone_number,address,city,state,postal_code,country
3000,3003,Title,first_name,last_name,61,GENDER,email,4,20281.18,ip_address,phone_number,address,city,state,postal_code,country
4001,4004,Title,first_name,last_name,59,GENDER,email,2,25929.55,ip_address,phone_number,address,city,state,postal_code,country
5002,5005,Title,first_name,last_name,42,GENDER,email,3,14398.92,ip_address,phone_number,address,city,state,postal_code,country
6003,6006,Title,first_name,last_name,47,GENDER,email,0,25806.16,ip_address,phone_number,address,city,state,postal_code,country
7004,7007,Title,first_name,last_name,34,GENDER,email,1,46225.20,ip_address,phone_number,address,city,state,postal_code,country
8005,8008,Title,first_name,last_name,55,GENDER,email,0,30364.56,ip_address,phone_number,address,city,state,postal_code,country
9005,9009,Title,first_name,last_name,29,GENDER,email,2,45918.51,ip_address,phone_number,address,city,state,postal_code,country
10006,10010,Title,first_name,last_name,66,GENDER,email,1,45466.85,ip_address,phone_number,address,city,state,postal_code,country
10913,10917,Mrs,Merilyn,Szymon,68,FEMALE,mszymonp6@ucoz.com,3,32938.82,109.130.101.200,818-623-6108,9 Kim Court,Vale de Santarém,Santarém,2005-033,Portugal
11007,11011,Title,first_name,last_name,34,GENDER,email,1,29887.94,ip_address,phone_number,address,city,state,postal_code,country
11927,11932,Mrs,Merilyn,Szymon,44,FEMALE,mszymonpk@technorati.com,1,49974.30,216.14.101.235,630-111-3228,8105 Butterfield Parkway,Shucheng Chengguanzhen,NaN,NaN,China
12007,12012,Title,first_name,last_name,41,GENDER,email,2,37993.65,ip_address,phone_number,address,city,state,postal_code,country
13008,13013,Title,first_name,last_name,59,GENDER,email,4,37320.06,ip_address,phone_number,address,city,state,postal_code,country

In [ ]:
#use this to keep the first duplicate and remove the duplicate data
df.drop_duplicates(subset=['first_name', 'last_name'], keep='first', inplace=True)

In [ ]:
df.shape

(13995, 16)

#Age

In [ ]:
df['Age'].values

array(['63', '29', '52', ..., '35', '31', '31'], dtype=object)

In [ ]:
df['Age'].isnull().sum()

np.int64(3)

In [ ]:
df[df['Age'].isnull()]

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
8,10,Mrs,Netta,Care,NaN,FEMALE,ncare9@yellowpages.com,0,43309.75,71.120.1.191,252-241-3132,9 Bay Terrace,San Antonio Oeste,NaN,8520,Argentina
25,27,Mrs,Robenia,Pincott,NaN,FEMALE,rpincottq@nature.com,4,48276.68,193.193.155.69,114-628-4673,207 Ramsey Center,Balakliya,NaN,NaN,Ukraine
40,42,Dr,Giulio,Suero,NaN,MALE,gsuero15@businessinsider.com,0,24038.30,8.174.231.224,336-199-1673,7 Dwight Pass,Pubal,NaN,NaN,South Korea

In [ ]:
df['Age'] = df['Age'].fillna('N/A')

In [ ]:
df['Age'].isnull().sum()

np.int64(0)

#Gender

In [ ]:
df['gender'].values

array(['MALE', 'MALE', 'FEMALE', ..., 'FEMALE', 'MALE', 'FEMALE'],
      dtype=object)

In [ ]:
df['gender'].isnull().sum()

np.int64(211)

In [ ]:
df[df['gender'].isnull()]

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,state,postal_code,country
120,123,Ms,Renault,Parkman,46,NaN,rparkman3e@pagesperso-orange.fr,1,34970.68,123.97.159.171,575-138-1528,33 Warbler Street,Yorosso,NaN,NaN,Mali
146,149,Mr,Halimeda,McFie,35,NaN,hmcfie44@csmonitor.com,3,17861.83,99.146.208.222,249-451-9197,242 Steensland Circle,Pangkalan,NaN,NaN,Indonesia
177,180,Mr,Jordan,Idell,53,NaN,jidell4z@imdb.com,4,49071.48,243.90.252.111,649-762-3725,87 Green Parkway,Bulog,NaN,2419,Philippines
334,337,Dr,Chen,Taillard,62,NaN,ctaillard9c@hhs.gov,0,33276.04,64.4.175.99,138-932-1043,66025 Norway Maple Way,Olutanga,NaN,7041,Philippines
354,357,Ms,Butch,Saladin,46,NaN,bsaladin9w@about.me,1,18980.79,41.143.89.133,265-394-6152,93181 Pankratz Plaza,Sumurber,NaN,NaN,Indonesia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13783,13789,N/A,Tyrone,Lancaster,68,NaN,tlancasterlj@foxnews.com,2,25362.93,138.111.25.127,656-595-6493,49535 Thackeray Lane,Korniyivka,NaN,NaN,Ukraine
13839,13845,N/A,Claiborne,Tredger,36,NaN,ctredgern3@vinaora.com,4,31705.30,111.169.75.122,789-277-3769,90 Fisk Road,Gadang,NaN,NaN,Indonesia
13875,13881,N/A,Nerti,Hofner,46,NaN,nhofnero3@dot.gov,1,48817.47,42.85.137.61,171-435-1073,78 Elka Avenue,Dumbéa,NaN,98839,New Caledonia
13878,13884,Rev,Konstanze,Nanuccioi,29,NaN,knanuccioio6@paginegialle.it,3,29535.87,152.87.85.13,431-159-1584,649 Sherman Trail,Carahue,NaN,NaN,Chile
13974,13980,Dr,Thaddus,Godsafe,49,NaN,tgodsafequ@tinyurl.com,4,44878.56,229.222.98.103,837-639-5993,0 Parkside Court,Las Americas,Tamaulipas,88925,Mexico

In [ ]:
df['gender'] = df['gender'].fillna('unknown')

#Email

In [ ]:
df['email'].values

array(['etorre0@domainmarket.com', 'bdmiterko1@hexun.com',
       'mhelstrip3@purevolume.com', ..., 'sbrotherhoodrp@skyrock.com',
       'wobroganrq@clickbank.net', 'vwinsomrr@elegantthemes.com'],
      dtype=object)

In [ ]:
df['email'].isnull().sum()

np.int64(0)

In [ ]:
df['email'].duplicated().sum()

np.int64(0)

#Other members in Family

In [ ]:
df['Other members in Family'].values

array(['1', '3', '3', ..., '2', '0', 'Not Available'], dtype=object)

In [ ]:
df['Other members in Family'].isnull().sum()

np.int64(0)

#Annual Average Spend

In [ ]:
df['Annual Average Spend'].values

array([36945.54, 28282.48, 29868.55, ..., 31947.77, 17699.67, 22796.39])

In [ ]:
df['Annual Average Spend'].isnull().sum()

np.int64(0)

In [ ]:
df.columns

Index(['Customer Id', 'title', 'first_name', 'last_name', 'Age', 'gender',
       'email', 'Other members in Family', 'Annual Average Spend',
       'ip_address', 'phone_number', 'address', 'city', 'state', 'postal_code',
       'country'],
      dtype='object')

#ip_address

In [ ]:
df['ip_address'].values

array(['229.34.127.166', '144.68.113.44', '167.49.197.203', ...,
       '205.111.252.186', '191.40.46.71', '102.49.86.71'], dtype=object)

In [ ]:
df['ip_address'].isnull().sum()

np.int64(0)

#Phone_number

In [ ]:
df['phone_number'].values

array(['890-424-8695', '964-985-5176', '375-528-2018', ...,
       '404-365-1886', '745-344-9601', '224-869-6773'], dtype=object)

In [ ]:
df['phone_number'].isnull().sum()

np.int64(0)

In [ ]:
df['phone_number'].duplicated().sum()

np.int64(0)

#Address

In [ ]:
df['address'].values

array(['265 Gulseth Plaza', '3555 Springs Trail', '8713 Jenifer Terrace',
       ..., '23 Maywood Hill', '8 Chinook Trail', '433 Wayridge Place'],
      dtype=object)

In [ ]:
df['address'].isnull().sum()

np.int64(0)

#City

In [ ]:
df['city'].values

array(['Nezhinka', 'Bagdadi', 'Żółkiewka', ..., 'Ar Rumaythīyah',
       'Behābād', 'Kitapak'], dtype=object)

In [ ]:
df['city'].isnull().sum()

np.int64(0)

#State

In [ ]:
df['state'].values

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [ ]:
df['state'].isnull().sum()

np.int64(11720)

In [ ]:
#drop the state columns bcz it has more null values
#state is not important
df = df.drop(columns=['state'],inplace=False)

In [ ]:
df.columns

Index(['Customer Id', 'title', 'first_name', 'last_name', 'Age', 'gender',
       'email', 'Other members in Family', 'Annual Average Spend',
       'ip_address', 'phone_number', 'address', 'city', 'postal_code',
       'country'],
      dtype='object')

#Postal_code

In [ ]:
df['postal_code'].values

array(['460536', nan, '22-335', ..., nan, nan, '6711'], dtype=object)

In [ ]:
df['postal_code'].isnull().sum()

np.int64(7278)

In [ ]:
df[df['postal_code'].isnull()]

,Customer Id,title,first_name,last_name,Age,gender,email,Other members in Family,Annual Average Spend,ip_address,phone_number,address,city,postal_code,country
1,2,Ms,Bartholemy,Dmiterko,29,MALE,bdmiterko1@hexun.com,3,28282.48,144.68.113.44,964-985-5176,3555 Springs Trail,Bagdadi,NaN,Georgia
3,5,Dr,Aeriell,Doran,41,FEMALE,adoran4@umich.edu,1,14854.94,108.236.57.123,345-601-9087,240 Barnett Lane,Paico,NaN,Peru
5,7,Dr,Silas,Lundon,33,MALE,slundon6@tiny.cc,0,11525.89,46.32.76.140,175-674-9947,086 Muir Plaza,Wensu,NaN,China
7,9,Mr,Abe,Glencorse,22,MALE,aglencorse8@tmall.com,2,21292.21,254.238.79.5,285-104-2478,01 Bonner Pass,Ngujuran,NaN,Indonesia
12,14,Rev,Carmita,Tallent,55,FEMALE,ctallentd@pinterest.com,4,49338.76,151.183.48.137,804-988-5699,1 Elgar Way,Banana Village,NaN,Kiribati
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13998,14004,Mr,Alis,Biasio,21,MALE,abiasiori@macromedia.com,1,43172.03,20.74.78.98,565-163-9435,7 Fair Oaks Alley,Rupe,NaN,Indonesia
14002,14008,Dr,Farrah,Bremond,35,FEMALE,fbremondrm@epa.gov,3,29005.40,231.213.238.144,670-158-1070,0404 Lighthouse Bay Pass,Đống Đa,NaN,Vietnam
14004,14010,Dr,Ugo,Bern,54,MALE,ubernro@cpanel.net,3,25798.50,224.98.187.220,400-589-7549,74022 Vahlen Park,Kaesŏng,NaN,North Korea
14005,14011,Mr,Star,Brotherhood,35,FEMALE,sbrotherhoodrp@skyrock.com,2,31947.77,205.111.252.186,404-365-1886,23 Maywood Hill,Ar Rumaythīyah,NaN,Kuwait
14006,14012,Rev,Woodie,O'Brogan,31,MALE,wobroganrq@clickbank.net,0,17699.67,191.40.46.71,745-344-9601,8 Chinook Trail,Behābād,NaN,Iran

In [ ]:
df.shape

(13995, 15)

In [ ]:
df = df.drop(columns=['postal_code'])

#Country

In [ ]:
df['country'].values

array(['Russia', 'Georgia', 'Poland', ..., 'Kuwait', 'Iran',
       'Philippines'], dtype=object)

In [ ]:
df['country'].isnull().sum()

np.int64(0)

In [ ]:
df.to_csv('Customer_cleaned_data.csv',index=False)